server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: ECEnzm
    url: jdbc:postgresql://localhost:5432/quizzmaster
    username: postgres

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  mail:
    host: smtp.ionos.fr
    port: 587
    username: support@quizzmaster.fr
    password: quizzl2f1
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.ssl.enable: false
      connectiontimeout: 5000
      timeout: 3000
      writetimeout: 5000
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

